services:
  mediapult-transfer:
    build: .
    restart: unless-stopped
    ports:
      - 3005:3000
    environment:
      PORT: 3000
      DATA_DIRECTORY: /data
      UPLOAD_DIRECTORY: /data/uploads/shares
      DATABASE_URL: file:/data/mediapult-transfer.db?connection_limit=1
    volumes:
      - "./data:/data:Z"
#      - "./config.yaml:/opt/app/config.yaml:ro,Z"
